### ISSUE TITLE
Call to a member function exec_SELECTquery() on null

### ISSUE THREAD

**Issue by Elmos2018** [einpraegsam/powermail_cond#28]
Hi there, 

i installed powermail_cond and got the following error after trying to active a new record in a sys folder: 

(1/1) Error
Call to a member function exec_SELECTquery() on null

Typo3 Version: 9.5.0
Powermail Version: 6.1.0
Powermail_cond Version: latest (6.0.0)

**Comment by einpraegsam** [comment]
Thx for the feedback. We have to remove the old TYPO3_DB calls because they were dropped in T3 9

**Comment by einpraegsam** [comment]
I just pushed 3 commits to develop branch to fix this issue. Can you please give me feedback if this solves your problem?

**Comment by Elmos2018** [comment]
I tried this via terminal: 
composer require in2code/powermail_cond: dev-develop

- not working ;( 
How can i install / update your develop branch?

**Comment by Elmos2018** [comment]
Ok i figured it out ;) but still not working: 
i created a "Condition container" but when i try to click on "Create a new Condition" nothing happens. 
I get a lot of JS Errors in my Console 

VM21062 jsfunc.inline.js:244 Uncaught TypeError: Cannot read property 'hasErrors' of undefined
    at Object.processAjaxResponse (VM21062 jsfunc.inline.js:244)
    at Object.success (VM21062 jsfunc.inline.js:208)
    at fire (VM21058 jquery.js:3268)
    at Object.fireWith [as resolveWith] (VM21058 jquery.js:3398)
    at done (VM21058 jquery.js:9305)
    at XMLHttpRequest.<anonymous> (VM21058 jquery.js:9548)

**Comment by einpraegsam** [comment]
Thx again for your time. I spend also some time to fix some issues for TYPO3 9.5. Everything works as expected on my both test systems now (8.7 and 9.5). Can you confirm this now if you check the branch `develop` again?

**Comment by einpraegsam** [comment]
Thx again for your time. I spend also some time to fix some issues for TYPO3 9.5. Everything works as expected on my both test systems now (8.7 and 9.5). Can you confirm this now if you check the branch `develop` again?

**Comment by einpraegsam** [comment]
Should be fixed with powermail_cond 6.1.0

**Comment by Elmos2018** [comment]
Works like a Charm ;) THANK you VERY much!!!
